/// <reference types = "C:/Users/Freez/node_modules/@types/node" />

// @ts-ignore
import * as typescriptImport from "./typescript.js";
const typescript: any = typescriptImport;

// This file will create a d.ts folder for the modularClasses.ts file, 
// and will create a .js file for use in Clearscript under temp.js, and write it to Classes.cs;

import * as fs from "fs";
import path from "path";
import esbuild from "esbuild";
import os from "os";

// ============================================================================
// Configuration & Paths
// ============================================================================

const tsFolder = path.join(__dirname, "../../typescript");
const embedFolder = path.join(__dirname, "../../embed");
const input = path.join(__dirname, "modularClasses.ts");

// ============================================================================
// Process 1: Extract & prepare code
// ============================================================================

function extractCode(): string {
    const fileContent = fs.readFileSync(input, "utf8");
    const code = fileContent.split("// # Only Include Below")[1].trim();
    console.log("Extracted code from " + path.basename(input));
    return code;
}

// ============================================================================
// Process 2: Write definition files
// ============================================================================

function writeDef(code: string): void {
    const forDTS =
        `
// This file is auto generated by modularClassesOutput.ts.
// Do not edit this file directly, edit modularClasses.ts instead and run modularClassesOutput.ts to update this file.

${code.trim()}
`.trim();

    fs.writeFileSync(path.join(embedFolder, "typescript", "ts-defs", "modularJS.d.ts"), forDTS);
    fs.copyFileSync(
        path.join(__dirname, "modularCS.d.ts"),
        path.join(embedFolder, "typescript", "ts-defs", "modularCS.d.ts")
    );
    console.log("Definition files written");
}

// ============================================================================
// Process 3: Transpile TypeScript to JavaScript
// ============================================================================

function transpileToJS(code: string): string {
    let transpiledCode = "";
    try {
        transpiledCode = typescript.transpileModule(code, { module: typescript.ModuleKind.ESNext }).outputText;
        console.log("TypeScript transpiled successfully");
    } catch (e) {
        console.error("Transpilation error:", e);
        throw e;
    }
    return transpiledCode;
}

// ============================================================================
// Process 4: Write JavaScript utility file for review
// ============================================================================

function writeJSUtilityFile(jsCode: string): void {
    const temp = path.join(__dirname, "./output/toCSUtility.js");
    fs.writeFileSync(temp, `// This file is auto-generated for review purposes.\n\n${jsCode}`);
    console.log("JavaScript utility file written to " + path.basename(temp));
}

// ============================================================================
// Process 5: Minify JavaScript
// ============================================================================

function minifyJS(jsCode: string): string {
    const minified = esbuild.transformSync(jsCode, { loader: "js", minify: true }).code;
    console.log("JavaScript minified");
    return minified;
}

// ============================================================================
// Process 6: Update C# Classes file with minified JS
// ============================================================================

function updateCSClassesFile(minifiedCode: string): void {
    const csClasses = path.join(__dirname, "../../Classes.cs");
    const csFile = fs.readFileSync(csClasses, "utf-8");
    const newCsFile = csFile.split(os.EOL).map(line => {
        if (line.trim().startsWith("private const string EXTERNAL_UTILITY_JS = ")) {
            const startingWhitespace = line.match(/^(\s*)/)?.[0] ?? "";
            return `${startingWhitespace}private const string EXTERNAL_UTILITY_JS = """ ${minifiedCode.trim()} """;`;
        }
        return line;
    }).join(os.EOL);
    fs.writeFileSync(csClasses, newCsFile);
    console.log("C# Classes file updated with minified JavaScript");
}

// ============================================================================
// Main: Execute all processes in order
// ============================================================================

function main(): void {
    console.log("Starting compilation process...");
    console.log(`Input: ${path.basename(input)}`);

    // Step 1: Extract code from source file
    const code = extractCode();

    // Step 2: Write definition files
    writeDef(code);

    // Step 3: Transpile TypeScript to JavaScript
    const jsCode = transpileToJS(code);

    // Step 4: Write JavaScript utility file
    writeJSUtilityFile(jsCode);
    fs.writeFileSync(path.join(__dirname, "../../embed/prefix.js"), jsCode);

    // Step 5: Minify JavaScript
    const minifiedCode = minifyJS(jsCode);

    // Step 6: Update C# Classes file
    updateCSClassesFile(minifiedCode);

    console.log("Compilation complete!");
}

// ============================================================================
// Execute
// ============================================================================

main();