<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="ILRepacker" AfterTargets="Build">
		<ItemGroup>
			<!-- Define the secondary assemblies you want to merge -->
			 <InputAssemblies Include="$(OutputPath)*.dll" />
			<!-- <InputAssemblies Include="$(OutputPath)$(AssemblyName).dll" />
			<InputAssemblies Include="$(OutputPath)Clearscript.Core.dll" />
			<InputAssemblies Include="$(OutputPath)ClearScript.Core.dll" />
			<InputAssemblies Include="$(OutputPath)ClearScript.V8.dll" />
			<InputAssemblies Include="$(OutputPath)ClearScript.V8.ICUData.dll" />
			<InputAssemblies Include="$(OutputPath)ClearScript.Windows.Core.dll" />
			<InputAssemblies Include="$(OutputPath)ClearScript.Windows.dll" />
			<InputAssemblies Include="$(OutputPath)LetheJavascript.dll" />
			<InputAssemblies Include="$(OutputPath)Newtonsoft.Json.dll" /> -->
		</ItemGroup>

		<ILRepack
			LibraryPath="$(LimbusCompanyFolder)\BepInEx\core\"
			Parallel="true"
			Internalize="true"
			InputAssemblies="@(InputAssemblies)"
			TargetKind="SameAsPrimaryAssembly"
			OutputFile="$(OutputPath)../Merged/MergedOutput.dll"
		/>
	</Target>
</Project>